import pandas

from redcapmatchresolver.match_records import MatchRecord

class MatchRecordGenerator:
    __facility_addresses: list = ...
    __facility_phone_numbers: list = ...

    def __init__(
        self, facility_addresses: list, facility_phone_numbers: list
    ) -> None: ...
    def generate_match_record(self, row: pandas.Series) -> MatchRecord: ...
