from enum import Enum
from typing import Any

class MatchQuality(Enum):
    IGNORED: int = ...
    MATCHED_NOPE: int = ...
    MATCHED_NULL: int = ...
    MATCHED_EXACT: int = ...
    MATCHED_CASE_INSENSITIVE: int = ...
    MATCHED_ALPHA_NUM: int = ...
    MATCHED_SUBSTRING: int = ...
    MATCHED_FUZZY: int = ...
    MATCHED_CALCULATED: int = ...
    @classmethod
    def convert(cls: Any, match_str: str) -> Any: ...
    def good_enough(self) -> bool: ...
    def ignored(self) -> bool: ...
