from .redcap_report_reader import CrcReview as CrcReview, REDCapReportReader as REDCapReportReader
from .utilities import Utilities as Utilities

class REDCapMatchResolver:
    def __init__(self, db_filename: str = ...) -> None: ...
    def lookup_potential_match(self, match_block: str) -> CrcReview: ...
    def read_reports(self, import_folder: str) -> bool: ...
