class REDCapReportWriter:
    addendum: str
    def __init__(self) -> None:
        self.__log = None
        self.__reports = None
        ...

    def add_match(self, match: str) -> None: ...
    def num_reports(self) -> int: ...
    def write(self, report_filename: str = ...) -> tuple: ...
    @staticmethod
    def __ensure_safe_path(target_path: str) -> str: ...
