from datetime import datetime
from redcapmatchresolver.redcap_clinic import REDCapClinic as REDCapClinic
from typing import Union

class REDCapAppointment:
    def __init__(self, appointment_headers: list, appointment_info: list, clinics: Union[REDCapClinic, None] = ...) -> None: ...
    @staticmethod
    def applicable_header_fields(headers: list) -> list: ...
    @staticmethod
    def clean_up_date(date_string: Union[int, str, None] = ...) -> str: ...
    def csv(self) -> str: ...
    def date(self) -> Union[datetime, None]: ...
    def priority(self) -> int: ...
    def valid(self) -> bool: ...
    def value(self, field: str) -> str: ...
