import pandas

from redcapmatchresolver.redcap_appointment import (
    REDCapAppointment as REDCapAppointment,
)
from redcapmatchresolver.redcap_clinic import REDCapClinic as REDCapClinic

class REDCapPatient:
    __appointments: list = ...
    __dob_keywords: tuple[str] = ...
    __info_fields: tuple[str] = ...
    __non_appointment_fields: list = ...
    __phone_keywords: tuple[str] = ...
    __df: pandas.DataFrame = ...

    def __init__(self, df: pandas.DataFrame, clinics: REDCapClinic) -> None: ...
    def appointments(self) -> list: ...
    def best_appointment(self) -> REDCapAppointment | None: ...
    def __cleanup(self) -> None: ...
    def csv(self, columns: list | None = None, include_headers: bool = True) -> str: ...
    def __distinguish_fields(self, headers: list) -> tuple: ...
    def __find_appointments(self, clinics: REDCapClinic) -> None: ...
    def merge(self, other_patient: REDCapPatient) -> None: ...
    def same_as(self, other_patient: REDCapPatient) -> bool: ...
    def set_study_id(self, study_id: int | str) -> None: ...
    def to_df(self) -> pandas.DataFrame: ...
    def value(self, field: str) -> str | None: ...
