from datetime import datetime

import pandas

from redcapmatchresolver.redcap_clinic import REDCapClinic as REDCapClinic

class REDCapAppointment:
    __appointment_date_keywords: tuple[str] = ...
    __department_keywords: tuple[str] = ...
    __appointment_time_keywords: tuple[str] = ...
    __appointment_clinic: str = ...
    __appointment_date: str = ...
    __appointment_time: str = ...
    __priority: REDCapClinic | None = ...
    def __init__(
        self,
        df: pandas.DataFrame,
        clinics: REDCapClinic | None = ...,
    ) -> None: ...
    @staticmethod
    def applicable_header_fields(headers: list) -> list: ...
    @staticmethod
    def clean_up_date(date_string: int | str | None = ...) -> str: ...
    def csv(self) -> str: ...
    def date(self) -> datetime | None: ...
    def priority(self) -> int: ...
    def to_df(self) -> pandas.DataFrame: ...
    def valid(self) -> bool: ...
    def value(self, field: str) -> str: ...
    def __assign_priority(self, clinics: REDCapClinic | None) -> None: ...
