[project]
name = "redcapmatchresolver"
version = "1.6.8"
description = "Assists with human review of possible patient matches."
license = {file = 'LICENSE'}
readme = "README.md"
authors = [
    {name = "Kevin J. Delaney", email = "<kjdelaney@health.ucsd.edu>"},
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]

[project.urls]
documentation = "https://github.com/DBMI/REDCapMatchResolver"
homepage = "https://github.com/DBMI/REDCapMatchResolver"
repository = "https://github.com/DBMI/REDCapMatchResolver"

[tool.poetry]
name = "redcapmatchresolver"
package-mode = true
packages = [{include = "redcapmatchresolver", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.11, <4.0"
pandas = ">=2.2.0"
tabulate = "^0.9.0"
redcaputilities = {git = "https://github.com/DBMI/REDCapUtilities.git", rev="main"}
pyyaml = "^6.0.1"
usaddress = "*"

[tool.poetry.group.dev.dependencies]
autoflake = "*"
make = "*"
mkdocs = "*"
mkdocstrings = "*"
mkdocs-material = "*"
openpyxl = "*"
pandas = "*"
pandas-stubs = "*"
pep8-naming = "*"
pre-commit = "*"
pymdown-extensions = "*"
pytest = "^7.2.0"
pytest-github-actions-annotate-failures = "*"
pytest-cov = "*"
pyupgrade = "*"
ruff = "*"
setuptools = "<82"
typing-extensions = "^4.16.0"
typing = "*"
wheel = "*"

[tool.poetry.group.test.dependencies]
faker = "^15.3.4"
openpyxl = "^3.1.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = """\
    --cov-report term-missing \
    --no-cov-on-fail \
"""
pythonpath = [
  ".", "src", "src/redcapmatchresolver"
]
testpaths= ["tests"]

[tool.coverage.report]
fail_under = 100
exclude_lines = [
    'if TYPE_CHECKING:',
    'pragma: no cover'
]
