name: Test

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # Cleaner implementation using native actions instead of manual curl piping
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: "-color"

  lint-cruft:
    name: Check if automatic project update was successful
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Fail if .rej files exist as structure update was not successful
        run: test -z "$(find . -iname '*.rej')"

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/python-poetry-env
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run test suite
        run: poetry run pytest
